### ISSUE TITLE
Complete Tabs

### ISSUE THREAD

**Issue by jarydkrish** [HarvestProfit/harvest-profit-ui#13]
Right now [tabs](https://github.com/HarvestProfit/harvest-profit-ui/blob/815a3cc68ccf8516240590be221f436d7b63cf4a/src/layout/Tabs.js) don't really do anything.

We should probably change that. One of the examples we could take inspiration from is the concept of [TabContent](https://github.com/reactstrap/reactstrap/blob/adc87360e6d60729280a0c354f03d0532cf2de8e/src/TabContent.js) and [TabPane](https://github.com/reactstrap/reactstrap/blob/adc87360e6d60729280a0c354f03d0532cf2de8e/src/TabPane.js) from the reactstrap project. 

It works by using [context](https://reactjs.org/docs/context.html), which allows us to add a `visible` or `active` css class based on the state of the parent.

All tab content should be rendered on the page, even if the tab isn't visible. No rendering `null`.

**Comment by humphreyja** [comment]
closing in favor for tab switcher components.  Not quite as much magic but gets the job done.
