### ISSUE TITLE
Write tests for FilterDropdown

### ISSUE THREAD

**Issue by jarydkrish** [HarvestProfit/harvest-profit-ui#14]
We currently don't have any tests for our FilterDropdown. We should probably have some of those.

For examples on how to write tests for that kind of component, see both the [InputString tests](https://github.com/HarvestProfit/harvest-profit-ui/blob/master/test/forms/InputString.test.js) and the [Dropdown tests](https://github.com/HarvestProfit/harvest-profit-ui/blob/master/test/forms/Dropdown.test.js)

**Comment by humphreyja** [comment]
done in latest PR
