### ISSUE TITLE
dropdowns pass entire object as second option to value

### ISSUE THREAD

**Issue by humphreyja** [HarvestProfit/harvest-profit-ui#41]
On change, it should pass the entire option object as a second value.  That way we can access additional metadata on the option on change.  Also this should be passed to custom components as well.

**Comment by jarydkrish** [comment]
While we at this, we should do two additional things:
- Accept `PropTypes.number` as the `value`
- Add documentation for the array that you can pass to the dropdown. Right now it's not clear that the object has to be formatted like `{ id: 'something', text: 'Something' }`
